#!/usr/bin/env python3
"""Generate THIRD-PARTY-NOTICES.md, the attribution file for third-party code we redistribute.

The project itself is AGPL-3.0-only (see LICENSE), but what a user receives from a release is not
only our code. Three separate bodies of third-party code travel with it, each arriving by a
different route and each needing a different kind of evidence, which is why this script has three
sections rather than one list:

  1. **Vendored browser assets** — files committed in this repository and served to the browser:
     `app/static/vendor/plotly.min.js` (plotly.js, MIT) and `app/static/app.css`, which is the
     *compiled output* of Tailwind CSS and daisyUI (both MIT). app.css is generated but committed,
     so it ships in every distribution form including a plain `git clone`.

  2. **Python runtime dependencies** — the wheels PyInstaller freezes into the macOS/Windows
     bundles and the Linux AppImage. The set is the `[project].dependencies` closure from
     pyproject.toml resolved through uv.lock; the `dev` dependency-group (pytest, playwright,
     httpx) is deliberately excluded because it is not bundled.

  3. **System libraries from the Debian/Ubuntu stack** — copied off the build host into the Linux
     AppImage by packaging/build-appimage.sh. This is the section with real obligations attached.
     The measured contents of a built AppDir are 119 shared libraries from 85 Ubuntu 24.04 source
     packages, and the licences are genuinely mixed: much of it is LGPL-2.1+ (GTK, GLib,
     gdk-pixbuf, Pango, WebKitGTK's core, libsoup, at-spi2), some is LGPL-3-or-GPL-2 (Nettle, GMP,
     libunistring, libidn2 — reached through GIO's GnuTLS module), and a large remainder is
     permissive (zlib, libpng, HarfBuzz, ICU, SQLite, fontconfig, OpenSSL …). See the "obligations"
     note below for what follows from that.

## Two generation paths, and only one of them is checkable

The important structural fact about this script: sections 1 and 2 can be regenerated anywhere from
the repository, and section 3 cannot.

**Sections 1 and 2 — repo-derived, and what `--check` actually validates.** The Plotly version and
copyright come from the banner comment at the top of the minified bundle, the Tailwind version from
the banner in app.css, the Tailwind/daisyUI versions from package-lock.json, the Python package set
from pyproject.toml resolved through uv.lock, and each Python licence from installed distribution
metadata via `importlib.metadata` (`License-Expression`, else `License`, else `License ::`
classifiers). Nothing reaches the network.

**Section 3 — host-derived, and NOT validated by `--check`.** The libraries are not in this
repository. They exist only on the Ubuntu 24.04 machine that runs build-appimage.sh, and the set
that ships is the transitive `ldd` closure of that script's LIB_ROOTS — the roots are 6 files, the
closure is 119. Enumerating it needs a built `dist/AppDir`, plus `dpkg -S`, `dpkg-query` and
`/usr/share/doc/*/copyright`, none of which exist on a developer checkout or a generic CI runner.

So section 3 is generated by a separate pass, `--refresh-system-libs`, run on the build host; it
writes `packaging/appimage-system-libraries.json`, which is committed. Ordinary runs of this script
read that JSON and render it. `--check` therefore verifies only that the committed notice matches
what sections 1 and 2 plus the *committed* JSON produce — it cannot tell whether the JSON itself
still describes the current build host. The generated file says so in as many words. Claiming
otherwise would be the overclaim this whole file exists to avoid.

## The obligations section 3 exists to discharge

LGPL-2.1 §6 and LGPL-3 §4 permit distributing a work that links LGPL libraries, provided the
recipient is told which libraries are included, is given their corresponding source, and can
relink. AGPL-3.0-only is compatible with both, so this is a notice obligation, not a conflict.
Three specifics shape what the generated file has to say:

  * **Four licence texts, not two.** LGPL-3 §4(b) requires the GNU GPL text alongside the LGPL
    text; the same is true of the LGPL-3-or-GPL-2 libraries. `licenses/` therefore carries verbatim
    LGPL-2.1, LGPL-3, GPL-2 and GPL-3.

  * **§6(b) is not available to us.** That option — rely on a copy of the library already on the
    user's machine — does not apply to an AppImage, whose entire point is to carry its own. The
    route taken is §6(d): offer equivalent source access from the same place the binary is
    distributed. That is why each entry carries a source-package NAME and VERSION rather than only
    a project homepage: those two strings are what make the offer answerable.

  * **libwebkit2gtk-4.1.so.0 is modified.** build-appimage.sh binary-patches two .rodata path
    strings in the copied library. §6(a) asks for corresponding source "including whatever changes
    were used", so pointing at Ubuntu's archive alone is incomplete; the notice states the
    modification and points at the patching code in our own published source.

## Debian copyright metadata is not reliably machine-readable

Section 3 records the source package and version for every library and points at the copyright
file, rather than trying to distil one licence string per package automatically. Several packages
here (cairo, fontconfig, pixman, libxslt, gnutls, libgcrypt, gstreamer, libjpeg-turbo, libtasn1)
have non-DEP-5 copyright files that a parser reads as blank. Worse, the `Files: *` stanza is
actively misleading for three of them — webkit2gtk declares BSD-2-clause though its core is
LGPL-2.1+, gobject-introspection declares GPL-2+ though the shipped library is LGPL-2+, and libidn2
declares GPL-3+ though the shipped library is LGPL-3+/GPL-2+. LICENSE_SUMMARY below is therefore a
reviewed-by-hand summary per source package, and `--refresh-system-libs` reports any package it has
no entry for instead of guessing.

Host-provided libraries carry no notice and are absent by construction: glibc and the loader,
libstdc++, libgcc_s, the GL/EGL/DRI stack and the X11/Wayland client libraries are excluded by
build-appimage.sh (HOST_PROVIDED in packaging/check-appdir-closure.py is the authoritative list),
and LGPL-2.1 §6 exempts major components of the operating system in any case.

## Usage

    uv run python scripts/generate_third_party_notices.py             # write the notice
    uv run python scripts/generate_third_party_notices.py --dry-run   # print it, write nothing
    uv run python scripts/generate_third_party_notices.py --check     # CI: fail if stale

    # on the Ubuntu 24.04 build host, after packaging/build-appimage.sh has produced dist/AppDir:
    python3 scripts/generate_third_party_notices.py --refresh-system-libs

Run the first three under `uv run` (or any synced environment): the Python licences are read from
installed distributions. The last needs only the stdlib and dpkg, which is why it is written to run
under the system python3 on a build host.

Output is deterministic — sorted, no timestamps, no host paths, and no value that depends on which
platform generated it — so `--check` tests staleness rather than environment.

Main items:
    read_plotly_banner() / read_tailwind_banner() / npm_versions()
                            vendored-asset versions, read back out of the shipped files.
    runtime_packages()      pyproject.toml + uv.lock → bundled distribution name → version.
    package_license()       one installed distribution → its licence, via importlib.metadata.
    PLATFORM_ONLY_LICENSES  licences for the Python packages installed on one platform only.
    LICENSE_SUMMARY         reviewed licence summary per Ubuntu source package (see above).
    scan_appdir()           build host only: dist/AppDir → the system-library records.
    render()                (the whole notice, warnings for stderr).
    main(argv)              CLI: render and write / print / compare, or refresh the host data.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import textwrap
import tomllib
from importlib import metadata
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent

OUTPUT_PATH = _REPO_ROOT / "THIRD-PARTY-NOTICES.md"
PYPROJECT_PATH = _REPO_ROOT / "pyproject.toml"
UV_LOCK_PATH = _REPO_ROOT / "uv.lock"
PACKAGE_LOCK_PATH = _REPO_ROOT / "package-lock.json"
PLOTLY_PATH = _REPO_ROOT / "app" / "static" / "vendor" / "plotly.min.js"
APP_CSS_PATH = _REPO_ROOT / "app" / "static" / "app.css"

# The distribution name of this project in uv.lock. It is the root of the dependency walk and is
# not itself a third party, so it never appears in the output.
PROJECT_NAME = "battery-sim"


# ── vendored browser assets ───────────────────────────────────────────────────

def read_plotly_banner() -> tuple[str, str]:
    """(version, copyright line) from the banner comment plotly.min.js carries at line 1.

    Read from the file rather than hardcoded so that dropping in a new plotly build updates the
    notice on the next run. Raises if the banner is not in the expected shape: a silently empty
    version would produce an attribution that names no version at all, which is worse than a
    failed script run.
    """
    head = PLOTLY_PATH.read_text(encoding="utf-8", errors="replace")[:2000]
    version = re.search(r"plotly\.js\s+v([0-9][^\s*]*)", head)
    copyright_line = re.search(r"^\s*\*\s*(Copyright[^\n]*?)\s*$", head, re.MULTILINE)
    if not version or not copyright_line:
        raise ValueError(
            f"{PLOTLY_PATH}: could not read the version/copyright banner — has the bundle been "
            "replaced with one built without the standard header?"
        )
    return version.group(1), copyright_line.group(1)


def read_tailwind_banner() -> str | None:
    """The Tailwind version from the banner that survives minification at line 1 of app.css.

    app.css is a build artifact, so its banner is the only in-file evidence of what produced it —
    and it names Tailwind only. daisyUI contributes styles to the same file but leaves no marker,
    which is exactly why the notice cannot be built from app.css alone; package-lock.json supplies
    the rest. Returns None if the banner is absent (a Tailwind release could stop emitting it),
    in which case the notice falls back to the lock file for the version too.
    """
    first_line = APP_CSS_PATH.read_text(encoding="utf-8", errors="replace")[:400]
    match = re.search(r"tailwindcss\s+v([0-9][^\s|]*)", first_line)
    return match.group(1) if match else None


def npm_versions() -> dict[str, str]:
    """Package name → resolved version, from package-lock.json's `packages` map.

    The lock file is the resolved truth; package.json only carries `^` ranges. Keys are the bare
    package names ("daisyui"), stripped of the "node_modules/" prefix the lock uses.
    """
    data = json.loads(PACKAGE_LOCK_PATH.read_text(encoding="utf-8"))
    versions: dict[str, str] = {}
    for key, entry in data.get("packages", {}).items():
        if not key.startswith("node_modules/"):
            continue
        name = key[len("node_modules/"):]
        # Nested installs appear as "node_modules/a/node_modules/b"; only the top-level entry is
        # the version we actually built with.
        if "/node_modules/" in name:
            continue
        if isinstance(entry, dict) and "version" in entry:
            versions[name] = entry["version"]
    return versions


# ── the Python runtime set ────────────────────────────────────────────────────

def _requirement_name(specifier: str) -> str:
    """The bare distribution name from a PEP 508 requirement string.

    Only the name is needed here — the version constraint is already resolved in uv.lock — so this
    stops at the first character that can follow a name rather than parsing the full grammar.
    """
    return re.split(r"[\s\[<>=!~;(]", specifier.strip(), maxsplit=1)[0]


def runtime_packages() -> dict[str, str]:
    """The distributions bundled at runtime: name → locked version, sorted by name.

    This is the pyproject `dependencies` closure resolved through uv.lock.

    Walks uv.lock's per-package `dependencies` (and the `optional-dependencies` groups selected by
    an extra, so `uvicorn[standard]` pulls in httptools/uvloop/websockets/…) breadth-first from the
    declared runtime requirements. The `dev` dependency-group is never entered: pytest, playwright
    and httpx are test-time tools and PyInstaller does not put them in a bundle, so listing them
    would over-claim what we redistribute.

    Platform markers are deliberately NOT evaluated. uvloop is Unix-only, and pywebview drags in
    pythonnet/clr-loader/cffi on Windows and pyobjc on macOS; since releases are built for all
    three platforms, the union across platforms is the honest set for a single notice file. The
    consequence is that some listed packages are not installed on whatever machine runs this
    script — render() handles that rather than treating it as an error.

    The version comes from uv.lock rather than from the installed distribution, so it is the same
    on every machine. That is what makes the generated file byte-stable and `--check` meaningful.
    """
    lock = tomllib.loads(UV_LOCK_PATH.read_text(encoding="utf-8"))
    by_name = {entry["name"]: entry for entry in lock.get("package", [])}

    project = tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))["project"]
    # (name, extras) pairs; extras select optional-dependency groups in the locked entry.
    pending: list[tuple[str, tuple[str, ...]]] = []
    for specifier in project.get("dependencies", []):
        name = _requirement_name(specifier)
        extras = re.search(r"\[([^\]]*)\]", specifier)
        pending.append((
            name,
            tuple(e.strip() for e in extras.group(1).split(",")) if extras else (),
        ))

    seen: set[tuple[str, tuple[str, ...]]] = set()
    resolved: dict[str, str] = {}
    while pending:
        name, extras = pending.pop()
        if (name, extras) in seen:
            continue
        seen.add((name, extras))
        entry = by_name.get(name)
        if entry is None:
            raise ValueError(
                f"{name!r} is a declared runtime dependency but is absent from {UV_LOCK_PATH.name}"
                " — the lock file is out of date; run `uv lock`."
            )
        resolved[name] = entry.get("version", "unknown")
        edges = list(entry.get("dependencies", []))
        optional = entry.get("optional-dependencies", {})
        for extra in extras:
            edges.extend(optional.get(extra, []))
        for edge in edges:
            pending.append((edge["name"], tuple(edge.get("extra", ()))))

    resolved.pop(PROJECT_NAME, None)
    return {name: resolved[name] for name in sorted(resolved)}


def package_license(name: str) -> str:
    """A human-readable licence for one installed distribution, or a marker if none is declared.

    Metadata is read in the order the packaging ecosystem moved through: PEP 639's
    `License-Expression` (an SPDX expression, what current builds emit), then the legacy free-text
    `License` field, then the `License ::` trove classifiers. The free-text field is truncated at
    the first line because some projects paste an entire licence into it.

    Raises PackageNotFoundError when the distribution is not installed; the caller decides what to
    do with that, because "not installed" has two very different causes — see render().
    """
    meta = metadata.distribution(name).metadata

    expression = meta.get("License-Expression")
    if expression:
        return expression.strip()

    legacy = meta.get("License")
    if legacy and legacy.strip() and legacy.strip() != "UNKNOWN":
        return legacy.strip().splitlines()[0].strip()

    classifiers = [
        value.split("::")[-1].strip()
        for value in (meta.get_all("Classifier") or [])
        if value.startswith("License ::")
    ]
    if classifiers:
        return " / ".join(sorted(set(classifiers)))

    # Stated rather than guessed: an unlicensed-looking distribution is a thing a human must go
    # look at, and silently writing "MIT" would be a false attribution.
    return "not declared in package metadata — verify upstream"


# Licences for the distributions that are in the runtime closure but are installed on only one
# platform, so `importlib.metadata` cannot see them on a Linux dev machine or in Linux CI.
#
# Without this table the generated file would depend on the platform that ran the generator, and
# `--check` would then fail for a macOS or Windows contributor purely because of where they ran
# it. The values are the licences these projects declare upstream; they are checked against the
# installed metadata whenever the script DOES run somewhere the package is present, and a
# disagreement is reported (see render()), so a stale entry here surfaces rather than persists.
PLATFORM_ONLY_LICENSES: dict[str, str] = {
    # Windows: pywebview's .NET/WinForms path.
    "pythonnet": "MIT",
    "clr-loader": "MIT",
    "cffi": "MIT",
    "pycparser": "BSD-3-Clause",
    "colorama": "BSD-3-Clause",
    # macOS: pywebview's Cocoa/WebKit path. All PyObjC packages ship under the same licence.
    "pyobjc-core": "MIT",
    "pyobjc-framework-cocoa": "MIT",
    "pyobjc-framework-quartz": "MIT",
    "pyobjc-framework-security": "MIT",
    "pyobjc-framework-uniformtypeidentifiers": "MIT",
    "pyobjc-framework-webkit": "MIT",
    # OpenBSD only per the lock's marker; listed for completeness of the closure.
    "qtpy": "MIT",
}


def package_homepage(name: str) -> str:
    """The "where to get it" URL for one distribution.

    Deliberately the PyPI project page rather than whatever Home-page/Project-URL the installed
    metadata happens to declare. Two reasons: PyPI is where the wheel we actually bundle came
    from, and it is derivable from the name alone — so the column is identical no matter which
    platform generated the file, which is what keeps `--check` from failing on platform noise.
    PyPI links onward to each project's own homepage and source.
    """
    return f"https://pypi.org/project/{name}/"


# ── the AppImage's system libraries ───────────────────────────────────────────
#
# This half runs on the Ubuntu build host, not on a developer checkout. See the module docstring
# for the split; the short version is that the AppImage's contents are the transitive `ldd` closure
# of build-appimage.sh's LIB_ROOTS (6 roots, 119 libraries as measured), which only exists once
# `dist/AppDir` has been laid out, and mapping a library back to a source package needs dpkg.

SYSTEM_LIBS_PATH = _REPO_ROOT / "packaging" / "appimage-system-libraries.json"
DEFAULT_APPDIR = _REPO_ROOT / "dist" / "AppDir"

# The bundled libraries live here inside the AppDir, and are copied from the identically named
# directory on the host. A few come from a subdirectory of it (libproxy's backend, for one), so the
# host lookup falls back to a recursive search rather than assuming a flat layout.
APPDIR_LIB_SUBPATH = "usr/lib/x86_64-linux-gnu"
HOST_LIB_DIR = Path("/usr/lib/x86_64-linux-gnu")

# Licence summary per Ubuntu SOURCE package, reviewed by hand against
# /usr/share/doc/<binary-package>/copyright.
#
# It is a curated table rather than a parse because the copyright files do not support one. Nine of
# the packages here are not DEP-5 at all (cairo, fontconfig, pixman, libxslt, gnutls28, libgcrypt20,
# gstreamer1.0, libjpeg-turbo, libtasn1-6) and a parser returns nothing for them. Three more are
# worse than unparseable — their `Files: *` stanza is misleading about the library we actually
# ship, and taking it at face value would put a false licence in a legal notice:
#
#   webkit2gtk             `Files: *` says BSD-2-clause; WebCore/WebKit's core is LGPL-2.1+.
#   gobject-introspection  `Files: *` says GPL-2+ (that covers the code generators, which we do
#                          not ship); the shipped libgirepository-1.0 is LGPL-2+.
#   libidn2                `Files: *` says GPL-3+ (the command-line tool); libidn2.so is
#                          LGPL-3+ or GPL-2+.
#
# Values name the licence(s) that apply to the shipped shared library, not to the whole source
# tree. Where a package is dual-licensed the disjunction is kept, because it is what the recipient
# gets to choose from. --refresh-system-libs fails on a source package with no entry here rather
# than emitting a blank cell.
LICENSE_SUMMARY: dict[str, str] = {
    # --- LGPL-2.x: the GTK/GNOME stack. These carry the §6 obligations.
    "at-spi2-core": "LGPL-2.1-or-later",
    "enchant-2": "LGPL-2.1-or-later",
    "fribidi": "LGPL-2.1-or-later",
    "gdk-pixbuf": "LGPL-2.1-or-later",
    "glib2.0": "LGPL-2.1-or-later",
    "gobject-introspection": "LGPL-2.0-or-later (shipped library; see note in the script)",
    "gtk+3.0": "LGPL-2.1-or-later",
    "libdatrie": "LGPL-2.1-or-later",
    "libgpg-error": "LGPL-2.1-or-later",
    "libgudev": "LGPL-2.0-or-later",
    "libgcrypt20": "LGPL-2.1-or-later",
    "libmanette": "LGPL-2.1-or-later",
    "libproxy": "LGPL-2.1-or-later",
    "librsvg": "LGPL-2.0-or-later",
    "libseccomp": "LGPL-2.1",
    "libsecret": "LGPL-2.1-or-later",
    "libsoup3": "LGPL-2.0-or-later",
    "libssh": "LGPL-2.1-or-later (with an OpenSSL linking exception)",
    "libthai": "LGPL-2.1-or-later",
    "pango1.0": "LGPL-2.0-or-later and LGPL-2.1-or-later",
    "systemd": "LGPL-2.1-or-later",
    "webkit2gtk": "LGPL-2.1-or-later and BSD-2-Clause (shipped library; see note in the script)",
    # --- LGPL-3-or-GPL-2: reached through GIO's GnuTLS module. These are why the GPL texts ship.
    "gmp": "LGPL-3.0-or-later OR GPL-2.0-or-later",
    "libidn2": "LGPL-3.0-or-later OR GPL-2.0-or-later (shipped library; see note in the script)",
    "libunistring": "LGPL-3.0-or-later OR GPL-2.0-or-later",
    "nettle": "LGPL-3.0-or-later OR GPL-2.0-or-later",
    # --- other copyleft or mixed
    "elfutils": "LGPL-3.0-or-later OR GPL-2.0-or-later (shipped libraries)",
    "gnutls28": "LGPL-2.1-or-later (library); GPL-3.0-or-later (tools, not shipped)",
    "graphite2": "LGPL-2.1-or-later OR MPL-1.1 OR GPL-2.0-or-later",
    "gst-plugins-base1.0": "LGPL-2.0-or-later",
    "gstreamer1.0": "LGPL-2.0-or-later",
    "hyphen": "GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1",
    "e2fsprogs": "LGPL-2.0-or-later (libcom_err; the tools are GPL-2 and are not shipped)",
    "util-linux": "LGPL-2.1-or-later (libblkid, libmount)",
    "keyutils": "LGPL-2.1-or-later (shipped library; the tools are GPL-2+)",
    "jbigkit": "GPL-2.0-or-later",
    "freetype": "FTL OR GPL-2.0-or-later",
    "cairo": "LGPL-2.1-or-later OR MPL-1.1",
    "libcap2": "BSD-3-Clause OR GPL-2.0-only",
    "libzstd": "BSD-3-Clause OR GPL-2.0-only",
    # --- permissive. Listed accurately rather than padded into the copyleft group: a notice that
    #     over-claims copyleft is as wrong as one that under-claims it.
    "brotli": "MIT",
    "bzip2": "bzip2 (BSD-style)",
    "curl": "curl (MIT/X-style)",
    "cyrus-sasl2": "BSD-3-Clause-Attribution",
    "dbus": "AFL-2.1 OR GPL-2.0-or-later",
    "duktape": "MIT",
    "expat": "MIT",
    "fontconfig": "fontconfig (MIT-style)",
    "gcc-14": "GPL-3.0-or-later WITH GCC-exception-3.1 (libatomic)",
    "harfbuzz": "MIT (Old Style)",
    "icu": "Unicode-3.0 (ICU)",
    "krb5": "MIT (krb5)",
    "lcms2": "MIT",
    "lerc": "Apache-2.0",
    "libbsd": "BSD-3-Clause",
    "libdeflate": "MIT",
    "libepoxy": "MIT",
    "libevdev": "MIT",
    "libffi": "MIT",
    "libjpeg-turbo": "IJG AND BSD-3-Clause AND Zlib",
    "libmd": "BSD-3-Clause",
    "libpng1.6": "libpng-2.0",
    "libpsl": "MIT",
    "libselinux": "public domain (libselinux)",
    "libtasn1-6": "LGPL-2.1-or-later",
    "libunwind": "MIT",
    "libwebp": "BSD-3-Clause",
    "libxau": "MIT",
    "libxdmcp": "MIT",
    "libxkbcommon": "MIT",
    "libxml2": "MIT",
    "libxslt": "MIT (X11-style)",
    "lz4": "BSD-2-Clause",
    "nghttp2": "MIT",
    "openldap": "OpenLDAP-2.8",
    "openssl": "Apache-2.0",
    "orc": "BSD-2-Clause AND BSD-3-Clause",
    "p11-kit": "BSD-3-Clause",
    "pcre2": "BSD-3-Clause (with the binary-package exception)",
    "pixman": "MIT",
    "rtmpdump": "LGPL-2.1-or-later (librtmp)",
    "sqlite3": "public domain",
    "tiff": "libtiff (BSD-style)",
    "xz-utils": "public domain (liblzma)",
    "zlib": "Zlib",
}

# Ubuntu's published source archive. `apt-get source` on a noble machine reaches the same trees;
# this URL is the durable form for a recipient who has no such machine.
UBUNTU_SOURCE_POOL = "https://archive.ubuntu.com/ubuntu/pool/"

# Libraries the AppImage modifies rather than copying verbatim, and what the modification is. LGPL
# §6(a) asks for corresponding source "including whatever changes were used in the work", so a
# pointer at Ubuntu's pristine source would be incomplete on its own — the change has to be named
# and its source located. Ours is in this repository, which is itself published under the AGPL.
MODIFIED_LIBRARIES: dict[str, str] = {
    "libwebkit2gtk-4.1.so.0":
        "Two NUL-terminated path strings in .rodata are rewritten in place, replacing the "
        "compiled-in helper-process directory `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1` with "
        "`/tmp/.battery-sim-webkit`, a symlink AppRun points at the mounted image. No code is "
        "changed and no byte offset moves (the replacement is NUL-padded to the original length). "
        "The patching code is `packaging/build-appimage.sh` (the \"repointing WebKit's helper "
        "path\" step), published with this project under the AGPL-3.0-only.",
}

# The verbatim licence texts shipped alongside the notice. LGPL-3 §4(b) requires the GNU GPL text
# to accompany the LGPL text, and the LGPL-3-or-GPL-2 libraries above make GPL-2 relevant too, so
# all four are carried rather than the two an LGPL-2.1-only bundle would need.
LICENSE_TEXTS = (
    ("LGPL-2.1", "licenses/LGPL-2.1.txt"),
    ("LGPL-3", "licenses/LGPL-3.txt"),
    ("GPL-2", "licenses/GPL-2.txt"),
    ("GPL-3", "licenses/GPL-3.txt"),
)


def _dpkg(args: list[str]) -> str:
    """Run a dpkg query and return stdout, or raise with a message naming what failed."""
    result = subprocess.run(args, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"{' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout


def scan_appdir(appdir: Path) -> list[dict]:
    """Enumerate a built AppDir's bundled libraries, grouped by Ubuntu SOURCE package.

    Build host only. For each `.so` under the AppDir's library directory: find the same file on the
    host, resolve the symlink (dpkg records the real file, not the SONAME link), ask `dpkg -S` which
    binary package owns it, then `dpkg-query` for that package's source name and source version.

    Grouped by source package rather than per-library because that is the unit a licence attaches
    to and the unit `apt-get source` takes — a per-.so table would repeat the same four fields
    eight times for gst-plugins-base and still not tell a recipient what to fetch.

    The source VERSION is carried, not just the name. Without it the §6(d) offer is unanswerable:
    "gnutls28" identifies a project, "gnutls28 3.8.3-1.1ubuntu3.6" identifies the code that is
    actually inside the binary.
    """
    lib_dir = appdir / APPDIR_LIB_SUBPATH
    if not lib_dir.is_dir():
        raise SystemExit(
            f"{lib_dir} does not exist — run packaging/build-appimage.sh first, or pass "
            f"--appdir. This mode enumerates a BUILT AppDir; it cannot work from sources."
        )

    by_source: dict[str, dict] = {}
    unmapped: list[str] = []
    for shipped in sorted(p for p in lib_dir.iterdir() if p.is_file() and ".so" in p.name):
        host_path = HOST_LIB_DIR / shipped.name
        if not host_path.exists():
            # Plugin backends live in a subdirectory of the host library dir (libproxy's, for
            # instance) even though the build flattens them into the AppDir.
            candidates = sorted(HOST_LIB_DIR.rglob(shipped.name))
            if not candidates:
                unmapped.append(shipped.name)
                continue
            host_path = candidates[0]

        owner = _dpkg(["dpkg", "-S", os.path.realpath(host_path)]).split(":")[0].strip()
        source, _, version = _dpkg(
            ["dpkg-query", "-W", "-f=${source:Package}\t${source:Version}", owner]
        ).partition("\t")
        entry = by_source.setdefault(
            source, {"source": source, "version": version, "binary_packages": [], "libraries": []}
        )
        if owner not in entry["binary_packages"]:
            entry["binary_packages"].append(owner)
        entry["libraries"].append(shipped.name)

    if unmapped:
        raise SystemExit(
            "these bundled libraries could not be traced to a host file, so their source package "
            "is unknown:\n  " + "\n  ".join(unmapped) + "\nA notice missing them would be "
            "incomplete; investigate rather than skipping them."
        )

    missing = sorted(s for s in by_source if s not in LICENSE_SUMMARY)
    if missing:
        raise SystemExit(
            "no LICENSE_SUMMARY entry for these source packages:\n  " + "\n  ".join(missing) +
            "\nRead /usr/share/doc/<binary-package>/copyright for each and add an entry. Do not "
            "trust the `Files: *` stanza without checking which files it actually covers."
        )

    records = []
    for source in sorted(by_source):
        entry = by_source[source]
        entry["binary_packages"] = sorted(entry["binary_packages"])
        entry["libraries"] = sorted(entry["libraries"])
        entry["license"] = LICENSE_SUMMARY[source]
        records.append(entry)
    return records


def refresh_system_libs(appdir: Path, out_path: Path) -> int:
    """Rewrite the committed system-library JSON from a built AppDir. Build host only."""
    records = scan_appdir(appdir)
    total = sum(len(r["libraries"]) for r in records)
    payload = {
        "//": (
            "Generated by scripts/generate_third_party_notices.py --refresh-system-libs on the "
            "Ubuntu 24.04 AppImage build host. Describes the libraries bundled in the Linux "
            "AppImage only. Regenerate after any change to what packaging/build-appimage.sh "
            "copies, or after a rebuild on an updated host."
        ),
        "distribution": "Ubuntu 24.04 (noble)",
        "library_count": total,
        "packages": records,
    }
    # sort_keys plus a trailing newline: the file is committed, so its diff should show only what
    # actually changed on the host.
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {out_path}: {total} libraries from {len(records)} source packages")
    print("Now re-run this script without --refresh-system-libs to regenerate the notice.")
    return 0


def load_system_libs() -> dict:
    """The committed host-derived system-library data.

    Read rather than recomputed: the data can only be produced on the build host, and this script
    must also run on a laptop and in CI. A missing file is an error rather than an empty section —
    silently omitting the LGPL libraries is the exact failure this file exists to prevent.
    """
    if not SYSTEM_LIBS_PATH.exists():
        raise SystemExit(
            f"{SYSTEM_LIBS_PATH} is missing. It is committed, and holds the AppImage's system "
            f"library inventory. Restore it from git, or regenerate it on the Ubuntu build host "
            f"with:\n  python3 scripts/generate_third_party_notices.py --refresh-system-libs"
        )
    return json.loads(SYSTEM_LIBS_PATH.read_text(encoding="utf-8"))


# ── rendering ─────────────────────────────────────────────────────────────────

def render() -> tuple[str, list[str]]:
    """(the whole notice, warnings for stderr).

    The notice is deterministic — sorted, no timestamps, no host paths, no value that depends on
    the platform it was generated on — which is what makes `--check` a test of staleness rather
    than of where CI happened to run. Anything the run noticed but must not write into the file
    comes back as the second element.
    """
    plotly_version, plotly_copyright = read_plotly_banner()
    npm = npm_versions()
    tailwind_version = read_tailwind_banner() or npm.get("tailwindcss", "unknown")
    daisyui_version = npm.get("daisyui", "unknown")

    out: list[str] = []
    add = out.append

    add("# Third-party notices")
    add("")
    add("The Home Battery Simulator is licensed under the GNU Affero General Public License,")
    add("version 3 only (see `LICENSE`). A distribution of it also contains third-party code")
    add("under other licences, listed below.")
    add("")
    add("This file is generated by `scripts/generate_third_party_notices.py`. Edit that script,")
    add("not this file.")
    add("")
    add("Three kinds of third-party code travel with a release. They do not all travel with every")
    add("release form, and — stated plainly, because it matters when reading the rest — they are")
    add("not all verified to the same standard:")
    add("")
    add("| Section | What it covers | Present in | Kept current by |")
    add("| --- | --- | --- | --- |")
    add("| 1 | Browser assets committed in this repository | every form, including a source "
        "checkout | regenerated from the repo; CI fails if stale |")
    add("| 2 | Python runtime dependencies | the PyInstaller bundles and the AppImage | "
        "regenerated from `uv.lock` and package metadata; CI fails if stale |")
    add("| 3 | System libraries taken from the build host | **the Linux AppImage only** | "
        "a snapshot of the Ubuntu build host, refreshed by hand; **not** checked by CI |")
    add("")

    # ── section 1 ──
    add("## 1. Vendored browser assets")
    add("")
    add("These files are committed in this repository and served to the browser as-is.")
    add("")
    add(f"### plotly.js {plotly_version}")
    add("")
    add("- File: `app/static/vendor/plotly.min.js`")
    add("- Licence: MIT")
    add(f"- {plotly_copyright}")
    add("- Full licence text: `app/static/vendor/plotly.min.js.LICENSE.txt`")
    add("- Upstream: https://github.com/plotly/plotly.js")
    add("")
    add(f"### Tailwind CSS {tailwind_version} and daisyUI {daisyui_version}")
    add("")
    add("- File: `app/static/app.css` — a generated file that is nonetheless committed, so it")
    add("  ships in every distribution form. It is the minified compilation of Tailwind CSS")
    add("  together with the daisyUI plugin; both projects' CSS is present in the output, though")
    add("  only Tailwind's banner comment survives minification.")
    add("- Licence: MIT (both projects)")
    add("- Copyright (c) Tailwind Labs, Inc. — https://github.com/tailwindlabs/tailwindcss")
    add("- Copyright (c) Pouya Saadeghi — https://github.com/saadeghi/daisyui")
    add("")
    add("The Tailwind and daisyUI toolchain is dev-time only (`package.json`); no Node.js code is")
    add("shipped or executed at runtime.")
    add("")

    # ── section 2 ──
    packages = runtime_packages()
    # Disagreements between PLATFORM_ONLY_LICENSES and installed metadata. Warned about on stderr
    # rather than written into the notice: the file's content must not vary with the platform that
    # generated it, or `--check` starts failing for reasons that have nothing to do with staleness.
    stale_entries: list[str] = []
    add("## 2. Python runtime dependencies")
    add("")
    out.extend(textwrap.wrap(
        f"The {len(packages)} distributions below are the resolved closure of the runtime "
        "dependencies declared in `pyproject.toml`, and are frozen into the desktop bundles by "
        "PyInstaller. The `dev` dependency-group (pytest, playwright, httpx) is not bundled and "
        "is not listed. Versions come from `uv.lock`; licences are read from each distribution's "
        "own metadata (PEP 639 `License-Expression`, else `License`, else `License ::` "
        "classifiers).",
        width=92,
    ))
    add("")
    add("Some entries are platform-specific: uvloop is not built for Windows, and pywebview")
    add("reaches pythonnet on Windows and PyObjC on macOS. The union across platforms is listed,")
    add("because one notice file covers all three builds.")
    add("")
    add("| Package | Version | Licence | Project |")
    add("| --- | --- | --- | --- |")
    for name, version in packages.items():
        fallback = PLATFORM_ONLY_LICENSES.get(name)
        try:
            licence = package_license(name)
            # The fallback table exists so this file does not depend on the generating platform;
            # when the package IS present, comparing the two is the only chance to notice that a
            # curated entry has gone stale. Reported, not corrected, because the local metadata is
            # the more authoritative of the two and the table is what should be edited.
            if fallback and fallback != licence:
                stale_entries.append(
                    f"{name}: PLATFORM_ONLY_LICENSES says {fallback!r}, installed metadata says "
                    f"{licence!r}"
                )
        except metadata.PackageNotFoundError:
            if fallback is None:
                raise SystemExit(
                    f"{name!r} is in the runtime set, is not installed here, and has no entry in "
                    f"PLATFORM_ONLY_LICENSES.\nEither run this script under `uv run` in a synced "
                    f"environment, or — if {name!r} is genuinely installed on one platform only — "
                    f"add it to that table in scripts/generate_third_party_notices.py."
                ) from None
            licence = fallback
        add(f"| {name} | {version} | {licence} | {package_homepage(name)} |")
    add("")

    # ── section 3 ──
    #
    # Rendered from the committed JSON, not from a live scan: see the module docstring. The prose
    # below is deliberate about saying which parts of this document are machine-checked and which
    # are a snapshot of a build host, because the two have different reliability and a reader of a
    # legal notice should not have to guess which they are looking at.
    system = load_system_libs()
    records = system["packages"]
    lgpl_records = [r for r in records if "LGPL" in r["license"]]

    add("## 3. System libraries bundled in the Linux AppImage")
    add("")
    add("**This section applies to the Linux AppImage only.** The macOS and Windows bundles use")
    add("the platform's own web view and carry none of these libraries, and neither does running")
    add("from source.")
    add("")
    add("**This section is a snapshot, not a machine-checked derivation.** Sections 1 and 2 above")
    add("are regenerated from files in this repository and CI verifies they are current. This one")
    add("cannot be: the libraries exist only on the Ubuntu build host, and identifying them needs")
    add("`dpkg` and a built AppDir. It is refreshed by running the generator with")
    add("`--refresh-system-libs` on that host, which writes")
    add("`packaging/appimage-system-libraries.json`; the freshness check cannot tell whether that")
    add("file still matches the host.")
    add("")
    add("To give a native window on a machine with nothing installed,")
    add("`packaging/build-appimage.sh` copies the GTK 3 / WebKit2GTK stack off the build host. It")
    add("starts from six roots — libwebkit2gtk-4.1, libjavascriptcoregtk-4.1, libgtk-3, libgdk-3,")
    add("libgirepository-1.0 and PyGObject's `_gi` extension, plus the plugin modules under")
    add("`gdk-pixbuf-2.0/`, `gio/modules/` and `webkit2gtk-4.1/` — and follows their transitive")
    add("`ldd` closure.")
    add("")
    # Wrapped rather than written as fixed lines: the counts are interpolated, so hand-wrapping
    # would leave a ragged line whenever they change width.
    out.extend(textwrap.wrap(
        f"As measured on the build host, that comes to **{system['library_count']} shared "
        f"libraries from {len(records)} {system['distribution']} source packages**, listed below.",
        width=92,
    ))
    add("")
    add("Libraries the image deliberately leaves to the user's machine are not bundled and are not")
    add("listed: the C library and dynamic loader, libstdc++, libgcc_s, the GL/EGL/DRI stack and")
    add("the X11/Wayland client libraries. They must match the user's kernel, graphics driver and")
    add("display server rather than the build host's. (`HOST_PROVIDED` in")
    add("`packaging/check-appdir-closure.py` is the authoritative list.)")
    add("")

    add("### Licensing and how to exercise your rights")
    add("")
    out.extend(textwrap.wrap(
        f"Of the {len(records)} source packages below, {len(lgpl_records)} are under the GNU "
        "Lesser General Public License — version 2.0 or 2.1, or the LGPL-3-or-GPL-2 form. The "
        "LGPL is compatible with this application's AGPL-3.0-only licence, so bundling them is "
        "permitted; what the LGPL additionally requires is that you be told they are there, that "
        "you can obtain their source, and that you can replace them. The rest of this subsection "
        "is that.",
        width=92,
    ))
    add("")
    add("**Licence texts.** Verbatim copies are in `licenses/` in this repository and are")
    add("distributed with the AppImage:")
    add("")
    for label, relative in LICENSE_TEXTS:
        add(f"- {label} — `{relative}`")
    add("")
    add("Both GPL texts are present because LGPL-3 §4(b) requires the GNU GPL to accompany the")
    add("LGPL, and because several bundled libraries (Nettle, GMP, libunistring, libidn2) are")
    add("offered under \"LGPL-3-or-later or GPL-2-or-later\", making GPL-2 a licence you may")
    add("actually choose.")
    add("")
    add("**Obtaining the source.** Release AppImages are built on `ubuntu-24.04`, pinned in")
    add("`.github/workflows/release.yml`. Every library below is the stock Ubuntu 24.04 (noble)")
    add("build of the source package and version named in the table, so those two strings identify")
    add("the exact code inside the binary. Three routes to it:")
    add("")
    add("1. On an Ubuntu 24.04 system, `apt-get source <source-package>=<version>`.")
    add(f"2. From Ubuntu's published archive at {UBUNTU_SOURCE_POOL} .")
    add("3. By written request to the address in this repository's README, for as long as the")
    add("   corresponding release is offered.")
    add("")
    add("The LGPL-2.1 §6(b) option — relying on a copy of the library already installed on your")
    add("machine — is not applicable here, since an AppImage exists precisely to carry its own.")
    add("The route above is the §6(d) equivalent-access one: the source is offered from the same")
    add("place the binary is, at no greater cost.")
    add("")
    add("**Relinking and replacing a library.** The libraries are dynamically linked, and are")
    add("plain `.so` files inside the image, so substituting your own build requires no rebuild of")
    add("this application:")
    add("")
    add("```")
    add("./Home-Battery-Simulator-x86_64.AppImage --appimage-extract")
    add("cp your-libfoo.so.1 squashfs-root/usr/lib/x86_64-linux-gnu/")
    add("./squashfs-root/AppRun")
    add("```")
    add("")
    add("**Modified libraries.** One bundled library is not a verbatim copy of the Ubuntu binary,")
    add("and LGPL §6(a) asks for the corresponding source including the changes made, so it is")
    add("stated here rather than left to be found:")
    add("")
    for name, description in sorted(MODIFIED_LIBRARIES.items()):
        # Wrapped so the committed Markdown stays readable in a plain editor and its diffs stay
        # line-sized; the descriptions are paragraph-length.
        wrapped = textwrap.wrap(f"`{name}` — {description}", width=96,
                                initial_indent="- ", subsequent_indent="  ")
        out.extend(wrapped)
    add("")
    add("Every other library is copied byte-for-byte from the Ubuntu package named in the table.")
    add("")

    add("### Bundled packages")
    add("")
    add("Grouped by Ubuntu source package, which is the unit a licence attaches to and the unit")
    add("`apt-get source` accepts. Licences are summarised per package from the Debian copyright")
    add("files, reviewed by hand: several of those files are not machine-readable, and for three")
    add("packages (webkit2gtk, gobject-introspection, libidn2) the file's `Files: *` stanza names")
    add("a licence that does not apply to the library we ship. The full copyright file for any")
    add("package is at `/usr/share/doc/<binary-package>/copyright` on an Ubuntu 24.04 system, and")
    add("in the source package.")
    add("")
    add("| Source package | Version | Licence (shipped libraries) | Libraries |")
    add("| --- | --- | --- | --- |")
    for record in records:
        libraries = ", ".join(f"`{name}`" for name in record["libraries"])
        add(f"| {record['source']} | {record['version']} | {record['license']} | {libraries} |")
    add("")
    return "\n".join(out) + "\n", stale_entries


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=OUTPUT_PATH,
                        help=f"where to write the notice (default {OUTPUT_PATH})")
    parser.add_argument("--dry-run", action="store_true",
                        help="print the notice to stdout without writing anything")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the file on disk differs from freshly generated "
                             "output (for CI); writes nothing. Note that this validates sections "
                             "1 and 2 against the repository, and section 3 only against the "
                             "committed JSON — it cannot tell whether that JSON is current")
    parser.add_argument("--refresh-system-libs", action="store_true",
                        help="BUILD HOST ONLY: enumerate a built AppDir with dpkg and rewrite "
                             "packaging/appimage-system-libraries.json. Needs Ubuntu 24.04 and "
                             "dist/AppDir; does not write the notice")
    parser.add_argument("--appdir", type=Path, default=DEFAULT_APPDIR,
                        help=f"AppDir to enumerate with --refresh-system-libs "
                             f"(default {DEFAULT_APPDIR})")
    args = parser.parse_args(argv)

    if args.dry_run and args.check:
        parser.error("--dry-run and --check are mutually exclusive")

    # The refresh is a separate job with a separate input, so it returns before any rendering:
    # it deliberately does NOT go on to rewrite the notice, because a build host and a synced
    # Python environment are not the same machine and the notice needs both.
    if args.refresh_system_libs:
        return refresh_system_libs(args.appdir, SYSTEM_LIBS_PATH)

    notice, warnings = render()
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)

    if args.dry_run:
        sys.stdout.write(notice)
        return 0

    if args.check:
        if not args.out.exists():
            print(f"FAIL: {args.out} does not exist; run this script without --check.")
            return 1
        if args.out.read_text(encoding="utf-8") != notice:
            print(f"FAIL: {args.out} is out of date with respect to the repository.")
            print("Regenerate it with:")
            print("  uv run python scripts/generate_third_party_notices.py")
            return 1
        print(f"ok: {args.out.name} is up to date")
        return 0

    args.out.write_text(notice, encoding="utf-8")
    system = load_system_libs()
    print(f"wrote {args.out} ({notice.count(chr(10))} lines, {len(runtime_packages())} Python "
          f"packages, {system['library_count']} system libraries from "
          f"{len(system['packages'])} source packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
