"""Resolve the build's commit SHA and write `app/_build_info.py`.

Main items:
    resolve_build_sha()     the SHA and where it came from, as a (sha, source) pair.
    render_build_info()     the generated module's source text.
    write_build_info()      resolve + render + write, returning the pair that was written.
    main()                  CLI entry point, used by the packaging scripts.

Run as `python packaging/build_info.py` before PyInstaller. The packaging scripts call it; it is
NOT called from the spec, because the spec is also executed by a bare `pyinstaller` invocation
and writing into the source tree as a side effect of that would be surprising.

## Resolution order, and why "unknown" is a real answer

    GITHUB_SHA          set by GitHub Actions on every runner. Preferred because it names the
                        commit the workflow checked out, which is authoritative even when the
                        checkout is a detached head or a shallow clone.
    git rev-parse       the local development case.
    "unknown"           neither available: a build from a source tarball with no .git, or a
                        machine without git installed.

The third case must NOT fail the build. Building from an exported tarball is legitimate, and
refusing to build there would trade a missing label for a broken release path. It must equally
not GUESS — reporting a SHA that was not verified is worse than reporting none, because the
value's only purpose is answering "which commit is this?" during support.

`git rev-parse` is run with `cwd` pinned to the repository root rather than inheriting the
caller's directory, so the answer does not depend on where the script was invoked from.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "app" / "_build_info.py"

UNKNOWN = "unknown"

# Enough to identify a commit by eye and in `git show`, short enough for a version string.
SHORT_SHA_LENGTH = 7


def resolve_build_sha() -> tuple[str, str]:
    """Return `(short_sha, source)` — see the module docstring for the order.

    `source` is one of "ci", "git" or "unknown", and is recorded alongside the SHA so a reader
    of the generated module can tell a verified value from a placeholder.
    """
    ci_sha = os.environ.get("GITHUB_SHA", "").strip()
    if ci_sha:
        return ci_sha[:SHORT_SHA_LENGTH], "ci"

    try:
        completed = subprocess.run(
            ["git", "rev-parse", f"--short={SHORT_SHA_LENGTH}", "HEAD"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        # No git binary, or it could not be executed. Not an error: see the docstring.
        return UNKNOWN, UNKNOWN

    if completed.returncode == 0:
        sha = completed.stdout.strip()
        if sha:
            return sha, "git"

    # git exists but this is not a repository (exported tarball), or HEAD is unborn.
    return UNKNOWN, UNKNOWN


def render_build_info(sha: str, source: str) -> str:
    """Return the full source text of the generated `app/_build_info.py`.

    The docstring of the generated file is kept in sync with the committed placeholder by hand.
    It is short on purpose — the reasoning lives in the committed version and in this module,
    and duplicating it into generated output would guarantee the two drift.
    """
    return f'''"""Build provenance: which commit this copy of the application was built from.

GENERATED by packaging/build_info.py at build time. The committed version of this file carries
placeholder values and the full explanation; do not edit this copy by hand.
"""

BUILD_SHA = {sha!r}
"""Short commit SHA the artifact was built from; "unknown" when it could not be determined."""

BUILD_SHA_SOURCE = {source!r}
"""Provenance of BUILD_SHA itself: "ci", "git", or "unknown"."""
'''


def write_build_info() -> tuple[str, str]:
    """Resolve the SHA, write `app/_build_info.py`, and return the `(sha, source)` written."""
    sha, source = resolve_build_sha()
    TARGET.write_text(render_build_info(sha, source), encoding="utf-8")
    return sha, source


def main() -> int:
    sha, source = write_build_info()
    print(f"build sha: {sha} (source: {source}) -> {TARGET.relative_to(ROOT)}")
    if source == UNKNOWN:
        # Visible, but not fatal — a tarball build is legitimate. See the module docstring.
        print(
            "note: no GITHUB_SHA and no git checkout; the artifact will not name its commit.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
